#!/bin/sh

TEMPLATECONF="$(pwd)/sources/meta-bouin/conf-odroid"
export TEMPLATECONF

. ./sources/poky/oe-init-build-env $1

if [ -n "$DISTRO" ]
then
        sed -e "s,DISTRO ?= \"poky\",DISTRO ?= '$DISTRO',g" -i conf/local.conf
fi
